name: Production Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 🚀 Test, Build & Deploy
    runs-on: ubuntu-latest
    outputs:
      install_outcome: ${{ steps.installOutcome.outputs.stepOutcome }}
      test_outcome: ${{ steps.testOutcome.outputs.stepOutcome }}
      build_outcome: ${{ steps.buildOutcome.outputs.stepOutcome }}
      deploy_outcome: ${{ steps.deployOutcome.outputs.stepOutcome }}
    steps:
      - name: 🔎 Checkout
        uses: actions/checkout@v3

      - name: 📟 Setup Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 📦 Install
        id: install
        run: npm install
      - id: installOutcome
        if: always()
        run: echo "::set-output name=stepOutcome::${{ steps.install.outcome }}"

      # - name: 🧪 Test
      #   id: test
      #   run: npm test
      # - id: testOutcome
      #   if: always()
      #   run: echo "::set-output name=stepOutcome::${{ steps.test.outcome }}"        

      - name: 🔧 Build
        id: build
        run: npm run build
        env:
          CI: false
      - id: buildOutcome
        if: always()
        run: echo "::set-output name=stepOutcome::${{ steps.build.outcome }}" 

      - name: 🚀 Deploy
        id: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - id: deployOutcome
        if: always()
        run: echo "::set-output name=stepOutcome::${{ steps.deploy.outcome }}" 

  notifyDiscord:
    needs: deploy
    name: 📢 Notify on Discord
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Conclusion
        uses: technote-space/workflow-conclusion-action@v3

      - name: Notify Success
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.WEBHOOK_URL }}
          username: "${{ github.repository }} - ${{ github.workflow }} #${{ github.run_number }}"
          avatar-url: "https://media.discordapp.net/attachments/857447804977152000/894758305690452039/success_kid.png"
          title: "✅ Deployment status: SUCCESS!"
          description: "🌐 [Visit the site](https://gotogromsp-20.github.io/GoToGroMSP-20/)."
          include-details: "false"
          color-success: "#2eb886"

      - name: Notify Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.WEBHOOK_URL }}
          username: "${{ github.repository }} - ${{ github.workflow }} #${{ github.run_number }}"
          avatar-url: "https://media.discordapp.net/attachments/857447804977152000/894760486439125042/explosion.png"
          title: "❌ Deployment status: FAILED . . ."
          description: |
            **INSTALL**
            `${{ needs.deploy.outputs.install_outcome }}`
            **TEST**
            `${{ needs.deploy.outputs.test_outcome }}`
            **BUILD**
            `${{ needs.deploy.outputs.build_outcome }}`
            **DEPLOY**
            `${{ needs.deploy.outputs.deploy_outcome }}`
          include-details: "false"
          color-failure: "#a30200"

      # - name: Notify Cancelled
      #   if: env.WORKFLOW_CONCLUSION == 'cancelled'
      #   uses: nobrayner/discord-webhook@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     discord-webhook: ${{ secrets.WEBHOOK_URL }}
      #     username: "${{ github.repository }} - ${{ github.workflow }} #${{ github.run_number }}"
      #     avatar-url: "https://media.discordapp.net/attachments/821500555696013343/925737666685837353/Blank-Nut-Button.png"
      #     title: "⚠️ Deployment status: CANCELLED . . ."
      #     description: "Click the link above to view details on GitHub."
      #     include-details: "false"
      #     color-cancelled: "#ffd513"
